### ISSUE TITLE
Remove bracket from current activity

### ISSUE THREAD

**Issue by nickm980** [nickm980/smallville#21]
Currently a bracket shows at the end of the current activity "}"

![Image](https://github.com/nickm980/smallville/assets/81270095/1dedf088-554a-4b21-9064-fc372b3a906a)

This should be a quick fix, just have to find where the extra bracket is coming from

**Comment by Elleriyc** [comment]
Hello, Can I be assigned to this ?

**Comment by Gauravvpnd** [comment]
Hey, i can work on this if you will assign me this.

**Comment by nickm980** [comment]
> Hello, Can I be assigned to this ?

Ok - I've assigned you
